storage: /verdaccio/storage

packages:
  '@texas2010/*':
    access: $all
    publish: $all
    unpublish: $all
  '**':
    access: $all
    publish: $all
    unpublish: $all

server:
  keepAliveTimeout: 60
